name: quran_app
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: ">=2.17.0-182.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.13
  google_fonts: ^3.0.1
  dartarabic: ^0.0.1-dev3
  dio: ^4.0.6
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  flutter_svg: 
  #sizer: ^2.0.15
  quran: ^1.1.2
  flutter_styled_toast: ^2.0.0
  sqflite: 
  just_audio: ^0.9.28
  hexcolor: ^2.0.7
  adhan: ^2.0.0-nullsafety.2
  #flutter_native_timezone: ^2.0.0
  geolocator: ^9.0.1
  flutter_countdown_timer: ^4.1.0
  hijri: ^3.0.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/quran-images/
    - assets/images/svg/
    - assets/images/svg/praying_time/
    - assets/sound/click/
    - assets/images/decor/
    - assets/images/times/


